bucketlist=["Travelling Nepal","Go bungee jumping","Riding Bike","Rock Climbing","Go back to childhood","Learn Newari","Camping","vibing alone","Zip line","Rafting"]
print(f"This is my bucketlist to {bucketlist[0]}")
print(f"This is my bucketlist to {bucketlist[1]}")
print(f"This is my bucketlist to {bucketlist[2]}")
print(f"This is my bucketlist to {bucketlist[3]}")
print(f"This is my bucketlist to {bucketlist[4]}")
print(f"This is my bucketlist to {bucketlist[5]}")
print(f"This is my bucketlist to {bucketlist[6]}")
print(f"This is my bucketlist to {bucketlist[7]}")
print(f"This is my bucketlist to {bucketlist[8]}")
print(f"This is my bucketlist to {bucketlist[9]}")
